name: Gulp CI/CD Workflow
on:
  push:
    branches:
      - main
      - master
permissions:
  contents: write
  pages: write
  id-token: write
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version:
          - 20
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
          
      - name: Cache Node Modules
        uses: actions/cache@v3
        with:
          path: node_modules
          key: ${{ runner.os }}-node-${{ matrix.node-version }}-${{ hashFiles('package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-${{ matrix.node-version }}-
          
      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2
        with:
          version: 1.4.549
          
      - name: Set up Pandoc
        uses: r-lib/actions/setup-pandoc@v2
          
      - name: Install Dependencies
        run: |
          npm install gulp
          npm install gulp-cli
          npm install @rollup/plugin-babel @rollup/plugin-commonjs @rollup/plugin-node-resolve @rollup/plugin-terser
          npm install gulp-zip gulp-header-comment gulp-eslint gulp-clean-css gulp-connect gulp-autoprefixer
          npm install sass
          npm install through2
          npm install yargs
          npm install glob
          npm install node-qunit-puppeteer
          npm install decktape
          
      - name: Build Project
        run: |
          npx gulp css
          npx gulp js
          npx gulp plugins

      - name: Install Google Chrome
        run: |
          sudo apt-get update
          sudo apt-get install -y google-chrome-stable
          
      - name: Run Tests
        run: npm test
        env:
          CI: true
          PUPPETEER_EXECUTABLE_PATH: /usr/bin/google-chrome-stable
          
      - name: Render Markdown and Quarto Files
        run: |
          for file in *.md; do
            if [ -f "$file" ] && [ "$file" != "README.md" ] && [ "$file" != "CONTRIBUTING.md" ] && [ "$file" != "LICENSE.md" ]; then
              echo "Rendering $file..."
              if ! quarto render "$file" --to revealjs; then
                echo "Warning: Failed to render $file, skipping..."
                continue
              fi
            fi
          done
          for file in *.qmd; do
            if [ -f "$file" ]; then
              echo "Rendering $file..."
              if ! quarto render "$file" --to revealjs; then
                echo "Warning: Failed to render $file, skipping..."
                continue
              fi
            fi
          done
          
      - name: Organize Presentations and Commit
        run: |
          mkdir -p presentations
          echo "Finding presentation files in the root:"
          find . -maxdepth 1 -type f \( -iname "*.md" -o -iname "*.qmd" -o -iname "*.html" \) \
            ! -iname "README.md" ! -iname "CONTRIBUTING.md" ! -iname "LICENSE.md"
          echo "Processing files..."
          for file in $(find . -maxdepth 1 -type f \( -iname "*.md" -o -iname "*.qmd" -o -iname "*.html" \) \
            ! -iname "README.md" ! -iname "CONTRIBUTING.md" ! -iname "LICENSE.md"); do
            file=${file#./}
            base=$(basename "$file" | sed 's/\.[^.]*$//')
            dest="presentations/$base"
            suffix=1
            while [ -d "$dest" ]; do
              if [ -f "$dest/$base.html" ] || [ -f "$dest/$base.md" ] || [ -f "$dest/$base.qmd" ]; then
                dest="presentations/${base}_$suffix"
                suffix=$((suffix+1))
              else
                break
              fi
            done
            mkdir -p "$dest"
            ext="${file##*.}"
            echo "Moving $file to $dest/$(basename "$dest").$ext"
            mv "$file" "$dest/$(basename "$dest").$ext"
          done
          echo "Git status after organizing:"
          git status
          if [[ -n "$(git status --porcelain)" ]]; then
            git config --global user.name "GitHub Actions Bot"
            git config --global user.email "actions@github.com"
            git add .
            git commit -m "Organize presentations and add generated PDFs/screenshots"
            git push
          else
            echo "No changes to commit"
          fi
      
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: .
          
  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4

      - name: Create .webloc file
        run: |
          echo '<?xml version="1.0" encoding="UTF-8"?>' > presentation.webloc
          echo '<plist version="1.0">' >> presentation.webloc
          echo '<dict>' >> presentation.webloc
          echo '  <key>URL</key>' >> presentation.webloc
          echo "  <string>${{ steps.deployment.outputs.page_url }}</string>" >> presentation.webloc
          echo '</dict>' >> presentation.webloc
          echo '</plist>' >> presentation.webloc
        env:
          PAGE_URL: ${{ steps.deployment.outputs.page_url }}
      
  generate-pdfs:
    needs: deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 2
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      
      - name: Install Decktape
        run: npm install -g decktape
      
      - name: Generate PDFs and Screenshots for Presentations
        env:
          REPO_NAME: ${{ github.repository }}
        run: |
          # Wait for GitHub Pages to be ready
          sleep 60
          
          # Loop over each presentation folder in presentations/
          for dir in presentations/*/; do
            pres=$(basename "$dir")
            if [ -f "$dir/$pres.html" ]; then
              htmlfile="$dir/$pres.html"
            elif ls "$dir"*.html 1> /dev/null 2>&1; then
              htmlfile=$(ls "$dir"*.html | head -n 1)
            else
              echo "No HTML file found in $dir, skipping..."
              continue
            fi
            url="https://${{ github.repository_owner }}.github.io/${REPO_NAME#*/}/$htmlfile"
            echo "Processing presentation '$pres' at $url"
            
            # Generate PDF in the presentation folder, named as presentation_name.pdf
            decktape reveal --chrome-arg="--no-sandbox" --size 1920x1080 "$url" "$dir/$pres.pdf"
            
            # Create a PNG subfolder inside the presentation folder
            mkdir -p "$dir/png"
            decktape reveal --chrome-arg="--no-sandbox" --size 1920x1080 "$url" "temp.pdf" --screenshots --screenshots-directory "$dir/png"
            
            # Rename screenshots to "presentation_name_slide_001.png", etc.
            cd "$dir/png"
            count=1
            for f in temp_*_1920x1080.png; do
              newname=$(printf "${pres}_slide_%03d.png" "$count")
              mv "$f" "$newname"
              count=$((count+1))
            done
            cd - >/dev/null
            rm temp.pdf
          done
      
      # Remove commit/push step here; changes were already committed in build.
